### ISSUE TITLE
Patch breaks `AppleQEMUGuestAgent` support.

### ISSUE THREAD

**Issue by reitermarkus** [ofawx/VmAssetCacheEnable#6]
The `AppleQEMUGuestAgent` binary seems to reference `kern.hv_vmm_present`.

**Comment by ofawx** [comment]
You're right! How annoying.

Ultimately I don't see any way around this unfortunately: with a kernel patching approach, disguising the various VMM strings in the kernel is going to end up with all-or-nothing outcomes at the application level.

If you or anyone else has an interest in porting these kernel patches to a Lilu plugin that targets AssetCache _specifically_, I'd be more than happy to lend my understanding of AssetCache, its binaries, and the VMM checks it does.

**Comment by reitermarkus** [comment]
Don't have any experience with Lilu, but I found this https://github.com/acidanthera/RestrictEvents/blob/master/RestrictEvents/SoftwareUpdate.cpp, which seems to spoof `kern.hv_vmm_present` as `1` specifically for the `softwareupdated` process. Might be useful as starting ground.

**Comment by ofawx** [comment]
I've had a crack along the lines of my own thinking. It **doesn't** work though, and I'm not sure if its my understanding of Lilu or AssetCache, so would be keen for someone else to investigate.
https://github.com/ofawx/deceivmm

**Comment by 82ghost82** [comment]
FeatureUnlock kext by acidanthera implemented the patch of content caching.
It was implemented after ofawx modified this repo.
I tried that kext with the boot-arg but I was never able to make it work and I didn't bother since I preferred this patching method.
Acidanthera has some very good developers, maybe we can open an issue in their bugtracker letting them know that it breaks AppleQEMUGuestAgent?
What do you think?
-----

Sorry to ask, but how can you test this break?

**Comment by reitermarkus** [comment]
> Sorry to ask, but how can you test this break?

What hypervisor are you using? I'm using Proxmox, which normally shows the VM's IPs but shows “Guest Agent not running” when this patch is active. Also, clean shutdown will not work from Proxmox. I either have to forcefully stop the VM or shut it down from within the VM.

In the VM, you can just check if the agent is running using `pgrep AppleQEMUGuestAgent`.

**Comment by reitermarkus** [comment]
I just tried the `FeatureUnlock` kext, and it weirdly still breaks `AppleQEMUGuestAgent` despite only patching the `AssetCache`.

**Comment by 82ghost82** [comment]
> In the VM, you can just check if the agent is running using `pgrep AppleQEMUGuestAgent`

Thank you, yes I can confirm that it breaks it.
I think a found a workaround: can you check if the process runs and if interacts correctly?

Copy AppleQEMUGuestAgent from /usr/libexec/ to your desktop.
Open it in a hex editor (HexFiend for example)
Search for vmm and replace the 2 instances with xxx
Replace the signature with the command: codesign -f -s - ~/Desktop/AppleQEMUGuestAgent
Run it from the terminal: ./AppleQEMUGuestAgent
Open a new terminal window leaving the previous one opened and run: pgrep AppleQEMUGuestAgent

**Comment by 82ghost82** [comment]
I opened a pr in acidanthera since you are reporting that the kext is working.
Since the patching method is the same the issue is the same:

https://github.com/acidanthera/bugtracker/issues/1910

**Comment by reitermarkus** [comment]
> since you are reporting that the kext is working

Actually the kext doesn't work for me, `sudo AssetCacheManagerUtil activate` fails with “Operation timed out”.

**Comment by reitermarkus** [comment]
Even if it did, you would still need the machdep.cpu.features VMM flag patch from this repo, I think.

**Comment by 82ghost82** [comment]
> Actually the kext doesn't work for me,

ok, I misread your message.
This isn't an issue, since the kern.hv_vmm_present patch method is the same as that in this repo.
Maybe I didn't enable the vmm rename when I tried it.
I will look into it more in details to see why it doesn't work.

**Comment by ofawx** [comment]
Well, thanks to both of you and khronokernel, there is no longer any need for this kernel patch! I will archive this repo and redirect people to acidanthera/FeatureUnlock
